# Generated by Django 4.2.2 on 2023-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
