# Generated by Django 4.2.2 on 2023-09-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
    ]
