# Generated by Django 4.2.2 on 2023-10-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
